function [macro_defs] = MacroDef()

persistent macro_defs_temp

% % 补充一下nan的情况（漏帧了）
% persistent OMNI_NULL_RCV
% OMNI_NULL_RCV = nan;
% macro_defs_temp.OMNI_NULL_RCV = OMNI_NULL_RCV;

% //Omni端数据的state定义

% #define OMNI_SEND_STATE_ERROR -100
persistent OMNI_SEND_STATE_ERROR
OMNI_SEND_STATE_ERROR = (-100);
macro_defs_temp.OMNI_SEND_STATE_ERROR = OMNI_SEND_STATE_ERROR;
% #define OMNI_SEND_STATE_EMPTY 0
persistent OMNI_SEND_STATE_EMPTY
OMNI_SEND_STATE_EMPTY = (0);
macro_defs_temp.OMNI_SEND_STATE_EMPTY = OMNI_SEND_STATE_EMPTY;
% #define OMNI_SEND_STATE_HEARTBEAT 10
persistent OMNI_SEND_STATE_HEARTBEAT
OMNI_SEND_STATE_HEARTBEAT = (10);
macro_defs_temp.OMNI_SEND_STATE_HEARTBEAT = OMNI_SEND_STATE_HEARTBEAT;
% #define OMNI_SEND_STATE_SYN 20
persistent OMNI_SEND_STATE_SYN
OMNI_SEND_STATE_SYN = (20);
macro_defs_temp.OMNI_SEND_STATE_SYN = OMNI_SEND_STATE_SYN;
% #define OMNI_SEND_STATE_ONLY_NOTE 30
persistent OMNI_SEND_STATE_ONLY_NOTE
OMNI_SEND_STATE_ONLY_NOTE = (30);
macro_defs_temp.OMNI_SEND_STATE_ONLY_NOTE = OMNI_SEND_STATE_ONLY_NOTE;
% #define OMNI_SEND_STATE_CURRENT_CORE 100
persistent OMNI_SEND_STATE_CURRENT_CORE
OMNI_SEND_STATE_CURRENT_CORE = (100);
macro_defs_temp.OMNI_SEND_STATE_CURRENT_CORE = OMNI_SEND_STATE_CURRENT_CORE;
% #define OMNI_SEND_STATE_LAST_CORE 101
persistent OMNI_SEND_STATE_LAST_CORE
OMNI_SEND_STATE_LAST_CORE = (101);
macro_defs_temp.OMNI_SEND_STATE_LAST_CORE = OMNI_SEND_STATE_LAST_CORE;
% #define OMNI_SEND_STATE_CURRENT_POSE 200
persistent OMNI_SEND_STATE_CURRENT_POSE
OMNI_SEND_STATE_CURRENT_POSE = (200);
macro_defs_temp.OMNI_SEND_STATE_CURRENT_POSE = OMNI_SEND_STATE_CURRENT_POSE;
% #define OMNI_SEND_STATE_LAST_POSE 201
persistent OMNI_SEND_STATE_LAST_POSE
OMNI_SEND_STATE_LAST_POSE = (201);
macro_defs_temp.OMNI_SEND_STATE_LAST_POSE = OMNI_SEND_STATE_LAST_POSE;
% #define OMNI_SEND_STATE_CURRENT_FORCE 300
persistent OMNI_SEND_STATE_CURRENT_FORCE
OMNI_SEND_STATE_CURRENT_FORCE = (300);
macro_defs_temp.OMNI_SEND_STATE_CURRENT_FORCE = OMNI_SEND_STATE_CURRENT_FORCE;
% #define OMNI_SEND_STATE_LAST_FORCE 301
persistent OMNI_SEND_STATE_LAST_FORCE
OMNI_SEND_STATE_LAST_FORCE = (301);
macro_defs_temp.OMNI_SEND_STATE_LAST_FORCE = OMNI_SEND_STATE_LAST_FORCE;
% #define OMNI_RCV_STATE_EMPTY 1000
persistent OMNI_RCV_STATE_EMPTY
OMNI_RCV_STATE_EMPTY = (1000);
macro_defs_temp.OMNI_RCV_STATE_EMPTY = OMNI_RCV_STATE_EMPTY;
% #define OMNI_RCV_STATE_HEARTBEAT 1010
persistent OMNI_RCV_STATE_HEARTBEAT
OMNI_RCV_STATE_HEARTBEAT = (1010);
macro_defs_temp.OMNI_RCV_STATE_HEARTBEAT = OMNI_RCV_STATE_HEARTBEAT;
% #define OMNI_RCV_STATE_TRIGGER 1020
persistent OMNI_RCV_STATE_TRIGGER
OMNI_RCV_STATE_TRIGGER = (1020);
macro_defs_temp.OMNI_RCV_STATE_TRIGGER = OMNI_RCV_STATE_TRIGGER;
% #define OMNI_RCV_STATE_CONFIG 1100
persistent OMNI_RCV_STATE_CONFIG
OMNI_RCV_STATE_CONFIG = (1100);
macro_defs_temp.OMNI_RCV_STATE_CONFIG = OMNI_RCV_STATE_CONFIG;
% #define OMNI_RCV_STATE_FORCE 1300
persistent OMNI_RCV_STATE_FORCE
OMNI_RCV_STATE_FORCE = (1300);
macro_defs_temp.OMNI_RCV_STATE_FORCE = OMNI_RCV_STATE_FORCE;
% #define OMNI_RCV_STATE_TORQUE 1301
persistent OMNI_RCV_STATE_TORQUE
OMNI_RCV_STATE_TORQUE = (1301);
macro_defs_temp.OMNI_RCV_STATE_TORQUE = OMNI_RCV_STATE_TORQUE;

macro_defs = macro_defs_temp;

end